// Wygenerowane przez tools/gen_bldui.py - nie edytowac.
//
// Panel budynku, budynek po budynku, wprost z exe:
//
//   * nazwa rekordu przycisku dla pary (komenda, TOBJ) -
//     `FUN_00529590`; ta sama komenda ma rozne grafiki
//     zaleznie od budynku i rasy,
//   * co panel maluje dla danego TOBJ - switche po
//     `panel+0xbf5` w `Update4PanelWB/SI` i `PaintCtrlObj/SI`.
#pragma once

namespace bldui {

// Nazwa rekordu przycisku. `si` bierze sie, gdy gra idzie
// trybem 3 (Silikony); inaczej rozstrzyga TOBJ, a gdy go nie
// ma na liscie - wariant domyslny.
struct But { int cmd; int tobj; const char *rec; };

inline const But *buttons(int &n)
{
    static const But k[] = {
        {   1,   -3, "BUT_SISTOP" },
        {   1,   -1, "BUT_DEFENCE" },
        {   1,    9, "BUT_STOPWORM" },
        {   1,   21, "BUT_STOPDOLPH" },
        {   1,   54, "BUT_STOPCONSTR" },
        {   1,   61, "BUT_STOPCONSTR" },
        {   1,   62, "BUT_STOPCONSTR" },
        {   1,   63, "BUT_STOPCONSTR" },
        {   1,   66, "BUT_STOPCONSTR" },
        {   1,   70, "BUT_STOPCONSTR" },
        {   1,   71, "BUT_STOPCONSTR" },
        {   1,   74, "BUT_STOPCONSTR" },
        {   1,   75, "BUT_STOPCONSTR" },
        {   1,   77, "BUT_STOPCONSTR" },
        {   1,   81, "BUT_STOPCONSTR" },
        {   2,   -3, "BUT_SIMOVE" },
        {   2,   -1, "BUT_MOVEBOAT" },
        {   2,    9, "BUT_MOVEWORM" },
        {   2,   21, "BUT_MOVEDOLPH" },
        {   2,   54, "BUT_MOVECONSTR" },
        {   2,   61, "BUT_MOVECONSTR" },
        {   2,   62, "BUT_MOVECONSTR" },
        {   2,   63, "BUT_MOVECONSTR" },
        {   2,   66, "BUT_MOVECONSTR" },
        {   2,   70, "BUT_MOVECONSTR" },
        {   2,   71, "BUT_MOVECONSTR" },
        {   2,   74, "BUT_MOVECONSTR" },
        {   2,   75, "BUT_MOVECONSTR" },
        {   2,   77, "BUT_MOVECONSTR" },
        {   2,   81, "BUT_MOVECONSTR" },
        {   3,   -3, "BUT_SIATTACK" },
        {   3,   -1, "BUT_ATTACK" },
        {   3,    9, "BUT_ATTACKWORM" },
        {   4,   -1, "BUT_RETREPAIR" },
        {   5,   -3, "BUT_SIGUARD" },
        {   5,   -1, "BUT_GUARD" },
        {   6,   -3, "BUT_SIPATROL" },
        {   6,   -1, "BUT_PATROL" },
        {   7,   -3, "BUT_SICAPTURE" },
        {   7,   -1, "BUT_CAPTURE" },
        {   8,   -1, "BUT_ZAPADLO" },
        {   8,    5, "BUT_SETMINE" },
        {   8,   11, "BUT_SETLIGHT" },
        {   8,   17, "BUT_SETSNARE" },
        {   9,   -1, "BUT_ATTACKDC" },
        {  10,   -3, "BUT_SIPARSHELL" },
        {  10,   -1, "BUT_ATTACKRAYS" },
        {  11,   -1, "BUT_PHANTOMON" },
        {  12,   -1, "BUT_PHANTOMOFF" },
        {  13,   -1, "BUT_REPSUBM" },
        {  14,   -3, "BUT_SIBUILD" },
        {  14,   -1, "BUT_BUILD" },
        {  15,   -1, "BUT_COMPLETEBUILD" },
        {  16,   -1, "BUT_DISMANTLING" },
        {  17,   -3, "BUT_SIRCLOAD" },
        {  17,   -1, "BUT_RCLOAD" },
        {  18,   -3, "BUT_SIRCUNLOAD" },
        {  18,   -1, "BUT_RCUNLOAD" },
        {  19,   -3, "BUT_SIREPLOAD" },
        {  19,   -1, "BUT_REPLOAD" },
        {  20,   -3, "BUT_SIREPUNLOAD" },
        {  20,   -1, "BUT_REPUNLOAD" },
        {  21,   -1, "BUT_RISE" },
        {  22,   -1, "BUT_FALL" },
        {  23,   -1, "BUT_TELEOBJ" },
        {  24,   -3, "BUT_SITELEPORT" },
        {  24,   -1, "BUT_TELETO" },
        {  25,   -1, "BUT_ATTACKLBOMB" },
        {  26,   -1, "BUT_ATTACKTLS" },
        {  27,   -1, "BUT_BLDMISSILE" },
        {  28,   -1, "BUT_BLDLASBOMB" },
        {  29,   -1, "BUT_BLDBOAT" },
        {  30,   -1, "BUT_BLDWORM" },
        {  31,   -1, "BUT_BLDDOLPH" },
        {  32,   -1, "BUT_SELFREP" },
        {  33,   -1, "BUT_RESEARCH" },
        {  34,   -1, "BUT_TRGOLD" },
        {  35,   -1, "BUT_ACTPSIHO" },
        {  36,   -1, "BUT_ACTISO" },
        {  37,   -1, "BUT_STOPISO" },
        {  38,   -1, "BUT_SETDESTINATION" },
        {  39,   -3, "BUT_SIDISSASSEMBLE" },
        {  39,   -1, "BUT_BREAKBUILD" },
        {  40,   -1, "BUT_CRACKINFO" },
        {  41,   -1, "BUT_GETINFO" },
        {  42,   -1, "BUT_VIEWZONE" },
        {  43,   -3, "BUT_SIATTACKZONE" },
        {  43,   -1, "BUT_ATTACKZONE" },
        {  44,   -3, "BUT_SIGUARDZONE" },
        {  44,   -1, "BUT_GUARDZONE" },
        {  45,   -3, "BUT_SISCOUT" },
        {  45,   -1, "BUT_SCOUT" },
        {  46,   -1, "BUT_BREAKAWAY" },
        {  47,   -3, "BUT_SIAI" },
        {  47,   -1, "BUT_BEHAVIOUR" },
        {  48,   -1, "BUT_TRADE" },
        {  49,   -1, "BUT_CONTAINER" },
        {  50,   -1, "BUT_BREAK" },
        {  51,   -1, "BUT_REPLINISH" },
        {  52,   -1, "BUT_ATTACKTRG" },
        {  53,   -1, "BUT_ENGACTIVEMODE" },
        {  54,   -1, "BUT_SATELLITE" },
        {  55,   -1, "BUT_SIDESTINATION" },
        {  56,   -1, "BUT_IFIELDOFF1" },
        {  57,   -1, "BUT_SICRACKINFO" },
        {  58,   -1, "BUT_TODIMENSION" },
        {  59,   -1, "BUT_GIVEENERGY" },
        {  60,   -1, "BUT_PRIORESTORATION" },
        {  61,   -1, "BUT_SIBUILDSUB" },
        {  62,   -1, "BUT_CREATEGATE" },
        {  63,   -1, "BUT_RCTOENERGY" },
        {  64,   -1, "BUT_SIGIVERC" },
        {  65,   -1, "BUT_SIRESEARCH" },
        {  66,   -1, "BUT_IFIELDON" },
        {  67,   -1, "BUT_SIVIEWZONE" },
        {  68,   -1, "BUT_BUILDLAB" },
        {  69,   -1, "BUT_IFIELDOFF2" },
        {  70,   -1, "BUT_SIGETINFO" },
        {  71,   -1, "BUT_FROMDIMENSION" },
        {  72,   -1, "BUT_SIREPLINISH" },
        {  73,   -1, "BUT_SINENGSHIELD" },
        {  74,   -1, "BUT_SIREPLPRIOR" },
        {  75,   -1, "BUT_SIGHOST" },
        {  76,   -1, "BUT_AMINE" },
        {  77,   -1, "BUT_TELETO" },
        {  79,   -1, "BUT_VQB" },
        {  80,   -3, "BUT_SIHOLD" },
        {  80,   -1, "BUT_HOLDBUILD" },
        {  81,   -3, "BUT_SIUNHOLD" },
        {  81,   -1, "BUT_UNHOLDBUILD" },
        {  82,   -3, "BUT_SISFIRE" },
        {  82,   -1, "BUT_BREAK" },
    };
    n = int(sizeof(k) / sizeof(k[0]));
    return k;
}

// **Przyciski budynku, gniazdo po gniezdzie.** Komendy sa
// z `TLOBaseTy` vtbl+0x34 (tryb 4 `GetPanelInfo`), a nazwy
// rekordow z `FUN_00529590(komenda, TOBJ)`. Gniazdo 0 zostaje
// puste - ustawia je kod przed switchem, po kategorii
// budynku, ktora powstaje dopiero w czasie dzialania gry.
struct Slot { int tobj; int slot; int cmd; const char *rec; };

inline const Slot *slots(int &n)
{
    static const Slot k[] = {
        {  50, 1,  29, "BUT_BLDBOAT" },
        {  50, 2,  38, "BUT_SETDESTINATION" },
        {  51, 1,  38, "BUT_SETDESTINATION" },
        {  53, 1,  33, "BUT_RESEARCH" },
        {  55, 1,  38, "BUT_SETDESTINATION" },
        {  58, 1,  34, "BUT_TRGOLD" },
        {  60, 1,  40, "BUT_CRACKINFO" },
        {  60, 2,  41, "BUT_GETINFO" },
        {  62, 1,   3, "BUT_ATTACK" },
        {  62, 2,  23, "BUT_TELEOBJ" },
        {  62, 3,  21, "BUT_RISE" },
        {  62, 4,   1, "BUT_STOPCONSTR" },
        {  62, 5,   2, "BUT_MOVECONSTR" },
        {  63, 1,   3, "BUT_ATTACK" },
        {  63, 2,  23, "BUT_TELEOBJ" },
        {  63, 3,  21, "BUT_RISE" },
        {  63, 4,   1, "BUT_STOPCONSTR" },
        {  63, 5,   2, "BUT_MOVECONSTR" },
        {  64, 1,  30, "BUT_BLDWORM" },
        {  64, 2,  38, "BUT_SETDESTINATION" },
        {  66, 1,   3, "BUT_ATTACK" },
        {  66, 2,  23, "BUT_TELEOBJ" },
        {  66, 3,  21, "BUT_RISE" },
        {  66, 4,   1, "BUT_STOPCONSTR" },
        {  66, 5,   2, "BUT_MOVECONSTR" },
        {  67, 1,  35, "BUT_ACTPSIHO" },
        {  68, 1,  27, "BUT_BLDMISSILE" },
        {  69, 1,  26, "BUT_ATTACKTLS" },
        {  70, 1,   3, "BUT_ATTACK" },
        {  70, 2,  23, "BUT_TELEOBJ" },
        {  70, 3,  21, "BUT_RISE" },
        {  70, 4,   1, "BUT_STOPCONSTR" },
        {  70, 5,   2, "BUT_MOVECONSTR" },
        {  71, 1,   3, "BUT_ATTACK" },
        {  71, 2,  23, "BUT_TELEOBJ" },
        {  71, 3,  21, "BUT_RISE" },
        {  71, 4,   1, "BUT_STOPCONSTR" },
        {  71, 5,   2, "BUT_MOVECONSTR" },
        {  73, 1,  31, "BUT_BLDDOLPH" },
        {  73, 2,  38, "BUT_SETDESTINATION" },
        {  74, 1,   3, "BUT_ATTACK" },
        {  74, 2,  23, "BUT_TELEOBJ" },
        {  74, 3,  21, "BUT_RISE" },
        {  74, 4,   1, "BUT_STOPCONSTR" },
        {  74, 5,   2, "BUT_MOVECONSTR" },
        {  75, 1,   3, "BUT_ATTACK" },
        {  75, 2,  23, "BUT_TELEOBJ" },
        {  75, 3,  21, "BUT_RISE" },
        {  75, 4,   1, "BUT_STOPCONSTR" },
        {  75, 5,   2, "BUT_MOVECONSTR" },
        {  76, 1,  37, "BUT_STOPISO" },
        {  78, 1,  28, "BUT_BLDLASBOMB" },
        {  78, 2,  25, "BUT_ATTACKLBOMB" },
        {  81, 1,   3, "BUT_ATTACK" },
        {  81, 2,  23, "BUT_TELEOBJ" },
        {  81, 3,  21, "BUT_RISE" },
        {  81, 4,   1, "BUT_STOPCONSTR" },
        {  81, 5,   2, "BUT_MOVECONSTR" },
        {  82, 1,  48, "BUT_TRADE" },
        {  82, 2,  49, "BUT_CONTAINER" },
        {  83, 1,  68, "BUT_BUILDLAB" },
        {  83, 2,  57, "BUT_SICRACKINFO" },
        {  83, 3,  70, "BUT_SIGETINFO" },
        {  84, 1,  65, "BUT_SIRESEARCH" },
        {  85, 1,  65, "BUT_SIRESEARCH" },
        {  86, 1,  65, "BUT_SIRESEARCH" },
        {  87, 1,  65, "BUT_SIRESEARCH" },
        {  88, 1,  65, "BUT_SIRESEARCH" },
        {  89, 1,  65, "BUT_SIRESEARCH" },
        {  90, 1,  65, "BUT_SIRESEARCH" },
        {  92, 1,  61, "BUT_SIBUILDSUB" },
        {  92, 2,  55, "BUT_SIDESTINATION" },
        {  93, 1,  67, "BUT_SIVIEWZONE" },
        {  95, 1,  63, "BUT_RCTOENERGY" },
        {  95, 2,  49, "BUT_CONTAINER" },
        {  97, 1,  59, "BUT_GIVEENERGY" },
        { 100, 1,  64, "BUT_SIGIVERC" },
        { 102, 1,  82, "BUT_BREAK" },
        { 103, 1,  82, "BUT_BREAK" },
        { 107, 1,  82, "BUT_BREAK" },
        { 108, 1,  62, "BUT_CREATEGATE" },
        { 109, 1,  66, "BUT_IFIELDON" },
        { 109, 2,  56, "BUT_IFIELDOFF1" },
        { 109, 3,  69, "BUT_IFIELDOFF2" },
        { 112, 1,  52, "BUT_ATTACKTRG" },
        { 113, 1,  82, "BUT_BREAK" },
        { 114, 1,  52, "BUT_ATTACKTRG" },
        { 114, 2,  79, "BUT_VQB" },
    };
    n = int(sizeof(k) / sizeof(k[0]));
    return k;
}

// Nazwa rekordu dla pary (komenda, TOBJ). Kolejnosc pytania
// jest ta sama, co w `PanelButtonRecord`: najpierw wariant
// Silikonow, potem wpis dla tego TOBJ, na koncu domyslny.
inline const char *record(int cmd, int tobj, bool si)
{
    int n = 0;
    const But *k = buttons(n);
    const char *def = "";
    for (int i = 0; i < n; ++i) {
        if (k[i].cmd != cmd) continue;
        if (si && k[i].tobj == -3) return k[i].rec;
        if (k[i].tobj == tobj) return k[i].rec;
        if (k[i].tobj == -1) def = k[i].rec;
    }
    return def;
}

// Krotki podpis do panelu - **moj**, z nazwy rekordu bez
// przedrostka. Gra pokazuje przy tych przyciskach grafike,
// a nie tekst.
inline const char *caption(int cmd)
{
    const char *r = record(cmd, -1, false);
    if (!r || !*r) return "?";
    if (r[4] == 'S' && r[5] == 'I') return r + 6;
    return r + 4;
}

// **Przyciski LODZI.** Ta sama maszyneria, co przy budynku:
// `STBoatC` vtbl+0x34 wypelnia te sama strukture, tylko
// switch idzie po typie jednostki (`this + 0x6f7`), a nie po
// TOBJ. Nazwy rekordow daje ten sam `PanelButtonRecord` -
// jego drugi argument to wspolna przestrzen: 1..40 lodzie,
// 50..115 budynki.
inline const Slot *unitSlots(int &n)
{
    static const Slot k[] = {
        {   1, 0,   2, "BUT_MOVEBOAT" },
        {   1, 1,   3, "BUT_ATTACK" },
        {   1, 2,   1, "BUT_DEFENCE" },
        {   1, 3,   4, "BUT_RETREPAIR" },
        {   1, 4,  47, "BUT_BEHAVIOUR" },
        {   1, 5,   6, "BUT_PATROL" },
        {   2, 0,   2, "BUT_MOVEBOAT" },
        {   2, 1,   3, "BUT_ATTACK" },
        {   2, 2,   1, "BUT_DEFENCE" },
        {   2, 3,   4, "BUT_RETREPAIR" },
        {   2, 4,  47, "BUT_BEHAVIOUR" },
        {   2, 5,   6, "BUT_PATROL" },
        {   3, 0,   2, "BUT_MOVEBOAT" },
        {   3, 1,   3, "BUT_ATTACK" },
        {   3, 2,   1, "BUT_DEFENCE" },
        {   3, 3,   4, "BUT_RETREPAIR" },
        {   3, 4,  47, "BUT_BEHAVIOUR" },
        {   3, 5,   6, "BUT_PATROL" },
        {   4, 0,   2, "BUT_MOVEBOAT" },
        {   4, 1,   3, "BUT_ATTACK" },
        {   4, 2,   1, "BUT_DEFENCE" },
        {   4, 3,   4, "BUT_RETREPAIR" },
        {   4, 4,  47, "BUT_BEHAVIOUR" },
        {   4, 5,   9, "BUT_ATTACKDC" },
        {   5, 0,   2, "BUT_MOVEBOAT" },
        {   5, 1,   3, "BUT_ATTACK" },
        {   5, 2,   1, "BUT_DEFENCE" },
        {   5, 3,   4, "BUT_RETREPAIR" },
        {   5, 4,  47, "BUT_BEHAVIOUR" },
        {   5, 5,   8, "BUT_SETMINE" },
        {   6, 0,   2, "BUT_MOVEBOAT" },
        {   6, 1,   3, "BUT_ATTACK" },
        {   6, 2,   1, "BUT_DEFENCE" },
        {   6, 3,   4, "BUT_RETREPAIR" },
        {   6, 4,  47, "BUT_BEHAVIOUR" },
        {   6, 5,   7, "BUT_CAPTURE" },
        {   7, 0,   2, "BUT_MOVEBOAT" },
        {   7, 1,  13, "BUT_REPSUBM" },
        {   7, 2,   1, "BUT_DEFENCE" },
        {   7, 3,   4, "BUT_RETREPAIR" },
        {   7, 4,  47, "BUT_BEHAVIOUR" },
        {   7, 5,  20, "BUT_REPUNLOAD" },
        {   8, 0,   2, "BUT_MOVEBOAT" },
        {   8, 1,  17, "BUT_RCLOAD" },
        {   8, 2,   1, "BUT_DEFENCE" },
        {   8, 3,   4, "BUT_RETREPAIR" },
        {   8, 4,  47, "BUT_BEHAVIOUR" },
        {   8, 5,  18, "BUT_RCUNLOAD" },
        {   9, 0,   2, "BUT_MOVEWORM" },
        {   9, 1,   3, "BUT_ATTACKWORM" },
        {   9, 2,   1, "BUT_STOPWORM" },
        {   9, 4,  47, "BUT_BEHAVIOUR" },
        {  10, 0,   2, "BUT_MOVEBOAT" },
        {  10, 1,   3, "BUT_ATTACK" },
        {  10, 2,   1, "BUT_DEFENCE" },
        {  10, 3,   4, "BUT_RETREPAIR" },
        {  10, 4,  47, "BUT_BEHAVIOUR" },
        {  10, 5,   6, "BUT_PATROL" },
        {  11, 0,   2, "BUT_MOVEBOAT" },
        {  11, 1,   3, "BUT_ATTACK" },
        {  11, 2,   1, "BUT_DEFENCE" },
        {  11, 3,   4, "BUT_RETREPAIR" },
        {  11, 4,  47, "BUT_BEHAVIOUR" },
        {  11, 5,   8, "BUT_SETLIGHT" },
        {  12, 0,   2, "BUT_MOVEBOAT" },
        {  12, 1,  14, "BUT_BUILD" },
        {  12, 2,   1, "BUT_DEFENCE" },
        {  12, 3,   4, "BUT_RETREPAIR" },
        {  12, 4,  47, "BUT_BEHAVIOUR" },
        {  12, 5,  16, "BUT_DISMANTLING" },
        {  13, 0,   2, "BUT_MOVEBOAT" },
        {  13, 1,   3, "BUT_ATTACK" },
        {  13, 2,   1, "BUT_DEFENCE" },
        {  13, 3,   4, "BUT_RETREPAIR" },
        {  13, 4,  47, "BUT_BEHAVIOUR" },
        {  13, 5,   6, "BUT_PATROL" },
        {  14, 0,   2, "BUT_MOVEBOAT" },
        {  14, 1,   3, "BUT_ATTACK" },
        {  14, 2,   1, "BUT_DEFENCE" },
        {  14, 3,   4, "BUT_RETREPAIR" },
        {  14, 4,  47, "BUT_BEHAVIOUR" },
        {  14, 5,   6, "BUT_PATROL" },
        {  15, 0,   2, "BUT_MOVEBOAT" },
        {  15, 1,   3, "BUT_ATTACK" },
        {  15, 2,   1, "BUT_DEFENCE" },
        {  15, 3,   4, "BUT_RETREPAIR" },
        {  15, 4,  47, "BUT_BEHAVIOUR" },
        {  15, 5,   6, "BUT_PATROL" },
        {  16, 0,   2, "BUT_MOVEBOAT" },
        {  16, 1,   3, "BUT_ATTACK" },
        {  16, 2,   1, "BUT_DEFENCE" },
        {  16, 3,   4, "BUT_RETREPAIR" },
        {  16, 4,  47, "BUT_BEHAVIOUR" },
        {  16, 5,   6, "BUT_PATROL" },
        {  17, 0,   2, "BUT_MOVEBOAT" },
        {  17, 1,   3, "BUT_ATTACK" },
        {  17, 2,   1, "BUT_DEFENCE" },
        {  17, 3,   4, "BUT_RETREPAIR" },
        {  17, 4,  47, "BUT_BEHAVIOUR" },
        {  17, 5,   8, "BUT_SETSNARE" },
        {  18, 0,   2, "BUT_MOVEBOAT" },
        {  18, 1,   3, "BUT_ATTACK" },
        {  18, 2,   1, "BUT_DEFENCE" },
        {  18, 3,   4, "BUT_RETREPAIR" },
        {  18, 4,  47, "BUT_BEHAVIOUR" },
        {  18, 5,   7, "BUT_CAPTURE" },
        {  19, 0,   2, "BUT_MOVEBOAT" },
        {  19, 1,  13, "BUT_REPSUBM" },
        {  19, 2,   1, "BUT_DEFENCE" },
        {  19, 3,   4, "BUT_RETREPAIR" },
        {  19, 4,  47, "BUT_BEHAVIOUR" },
        {  19, 5,  20, "BUT_REPUNLOAD" },
        {  20, 0,   2, "BUT_MOVEBOAT" },
        {  20, 1,  17, "BUT_RCLOAD" },
        {  20, 2,   1, "BUT_DEFENCE" },
        {  20, 3,   4, "BUT_RETREPAIR" },
        {  20, 4,  47, "BUT_BEHAVIOUR" },
        {  20, 5,  18, "BUT_RCUNLOAD" },
        {  21, 0,   2, "BUT_MOVEDOLPH" },
        {  21, 1,   3, "BUT_ATTACK" },
        {  21, 2,   1, "BUT_STOPDOLPH" },
        {  21, 4,  47, "BUT_BEHAVIOUR" },
        {  22, 0,   2, "BUT_MOVEBOAT" },
        {  22, 1,   3, "BUT_ATTACK" },
        {  22, 2,   1, "BUT_DEFENCE" },
        {  22, 3,   4, "BUT_RETREPAIR" },
        {  22, 4,  47, "BUT_BEHAVIOUR" },
        {  22, 5,  11, "BUT_PHANTOMON" },
        {  23, 0,   2, "BUT_MOVEBOAT" },
        {  23, 1,   3, "BUT_ATTACK" },
        {  23, 2,   1, "BUT_DEFENCE" },
        {  23, 3,   4, "BUT_RETREPAIR" },
        {  23, 4,  47, "BUT_BEHAVIOUR" },
        {  23, 5,  10, "BUT_ATTACKRAYS" },
        {  24, 0,   2, "BUT_MOVEBOAT" },
        {  24, 1,  14, "BUT_BUILD" },
        {  24, 2,   1, "BUT_DEFENCE" },
        {  24, 3,   4, "BUT_RETREPAIR" },
        {  24, 4,  47, "BUT_BEHAVIOUR" },
        {  24, 5,  16, "BUT_DISMANTLING" },
        {  25, 0,   2, "BUT_MOVEBOAT" },
        {  25, 1,  14, "BUT_BUILD" },
        {  25, 2,   1, "BUT_DEFENCE" },
        {  25, 3,  72, "BUT_SIREPLINISH" },
        {  25, 4,  47, "BUT_BEHAVIOUR" },
        {  26, 0,   2, "BUT_MOVEBOAT" },
        {  26, 1,  17, "BUT_RCLOAD" },
        {  26, 2,   1, "BUT_DEFENCE" },
        {  26, 3,  72, "BUT_SIREPLINISH" },
        {  26, 4,  47, "BUT_BEHAVIOUR" },
        {  26, 5,  18, "BUT_RCUNLOAD" },
        {  27, 0,   2, "BUT_MOVEBOAT" },
        {  27, 1,  20, "BUT_REPUNLOAD" },
        {  27, 2,   1, "BUT_DEFENCE" },
        {  27, 3,  72, "BUT_SIREPLINISH" },
        {  27, 4,  47, "BUT_BEHAVIOUR" },
        {  27, 5,  24, "BUT_TELETO" },
        {  28, 0,   2, "BUT_MOVEBOAT" },
        {  28, 1,   3, "BUT_ATTACK" },
        {  28, 2,   1, "BUT_DEFENCE" },
        {  28, 3,  72, "BUT_SIREPLINISH" },
        {  28, 4,  47, "BUT_BEHAVIOUR" },
        {  29, 0,   2, "BUT_MOVEBOAT" },
        {  29, 1,  16, "BUT_DISMANTLING" },
        {  29, 2,   1, "BUT_DEFENCE" },
        {  29, 3,  72, "BUT_SIREPLINISH" },
        {  29, 4,  47, "BUT_BEHAVIOUR" },
        {  29, 5,  24, "BUT_TELETO" },
        {  30, 0,   2, "BUT_MOVEBOAT" },
        {  30, 1,   3, "BUT_ATTACK" },
        {  30, 2,   1, "BUT_DEFENCE" },
        {  30, 3,  72, "BUT_SIREPLINISH" },
        {  30, 4,  47, "BUT_BEHAVIOUR" },
        {  31, 0,   2, "BUT_MOVEBOAT" },
        {  31, 1,   3, "BUT_ATTACK" },
        {  31, 2,   1, "BUT_DEFENCE" },
        {  31, 3,  72, "BUT_SIREPLINISH" },
        {  31, 4,  47, "BUT_BEHAVIOUR" },
        {  32, 0,   2, "BUT_MOVEBOAT" },
        {  32, 1,   3, "BUT_ATTACK" },
        {  32, 2,   1, "BUT_DEFENCE" },
        {  32, 3,  72, "BUT_SIREPLINISH" },
        {  32, 4,  47, "BUT_BEHAVIOUR" },
        {  33, 0,   2, "BUT_MOVEBOAT" },
        {  33, 1,   3, "BUT_ATTACK" },
        {  33, 2,   1, "BUT_DEFENCE" },
        {  33, 3,  72, "BUT_SIREPLINISH" },
        {  33, 4,  47, "BUT_BEHAVIOUR" },
        {  33, 5,   8, "BUT_ZAPADLO" },
        {  34, 0,   2, "BUT_MOVEBOAT" },
        {  34, 1,   3, "BUT_ATTACK" },
        {  34, 2,   1, "BUT_DEFENCE" },
        {  34, 3,  72, "BUT_SIREPLINISH" },
        {  34, 4,  47, "BUT_BEHAVIOUR" },
        {  34, 5,   7, "BUT_CAPTURE" },
        {  35, 0,   2, "BUT_MOVEBOAT" },
        {  35, 1,   3, "BUT_ATTACK" },
        {  35, 2,   1, "BUT_DEFENCE" },
        {  35, 3,  72, "BUT_SIREPLINISH" },
        {  35, 4,  47, "BUT_BEHAVIOUR" },
        {  36, 0,   2, "BUT_MOVEBOAT" },
        {  36, 2,   1, "BUT_DEFENCE" },
        {  36, 3,  72, "BUT_SIREPLINISH" },
        {  36, 4,  47, "BUT_BEHAVIOUR" },
        {  36, 5,  24, "BUT_TELETO" },
        {  37, 0,   2, "BUT_MOVEBOAT" },
        {  37, 1,   3, "BUT_ATTACK" },
        {  37, 2,   1, "BUT_DEFENCE" },
        {  37, 3,   4, "BUT_RETREPAIR" },
        {  37, 4,  47, "BUT_BEHAVIOUR" },
        {  37, 5,  11, "BUT_PHANTOMON" },
        {  38, 0,   2, "BUT_MOVEBOAT" },
        {  38, 1,   3, "BUT_ATTACK" },
        {  38, 2,   1, "BUT_DEFENCE" },
        {  38, 3,   4, "BUT_RETREPAIR" },
        {  38, 4,  47, "BUT_BEHAVIOUR" },
        {  38, 5,   6, "BUT_PATROL" },
        {  39, 0,   2, "BUT_MOVEBOAT" },
        {  39, 1,   3, "BUT_ATTACK" },
        {  39, 2,   1, "BUT_DEFENCE" },
        {  39, 3,   4, "BUT_RETREPAIR" },
        {  39, 4,  47, "BUT_BEHAVIOUR" },
        {  39, 5,   6, "BUT_PATROL" },
        {  40, 0,   2, "BUT_MOVEBOAT" },
        {  40, 1,   3, "BUT_ATTACK" },
        {  40, 2,   1, "BUT_DEFENCE" },
        {  40, 3,  72, "BUT_SIREPLINISH" },
        {  40, 4,  47, "BUT_BEHAVIOUR" },
    };
    n = int(sizeof(k) / sizeof(k[0]));
    return k;
}

// **Konstrukcje ruchome.** Budynki, ktore da sie podniesc,
// przestawic i zanurzyc - `TLOBaseTy` vtbl+0x34 bramkuje tym
// caly blok RISE / FALL / MOVECONSTR / STOPCONSTR / TELEOBJ.
// Ten sam zbior daje tablica dzwieku wiezyczki na postoju,
// wiec dwa niezalezne odczyty wskazuja te same budynki.
inline bool mobile(int tobj)
{
    static const unsigned char k[34] = {
        0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 0, 0, 0, 0, 0, 1, 0, 0
    };
    const int g = tobj - 50;
    return g >= 0 && g < 34 && k[g] != 0;
}

// Co panel pokazuje przy danym budynku.
struct Info { int tobj; const char *shows; const char *strings; };

inline const Info *info(int &n)
{
    static const Info k[] = {
        {  50, "koszt, postep, napis, grafika", "10021" },
        {  51, "koszt, postep, napis, grafika", "10003" },
        {  52, "amunicja, grafika", "" },
        {  53, "surowiec, nazwa surowca, napis, grafika", "10044" },
        {  54, "napis, grafika", "" },
        {  55, "napis, grafika", "" },
        {  56, "zloze", "" },
        {  57, "zloze", "" },
        {  58, "napis, grafika", "14006 14007 14008" },
        {  59, "", "" },
        {  60, "postep, grafika", "" },
        {  61, "", "" },
        {  62, "grafika", "" },
        {  63, "grafika", "" },
        {  64, "koszt, postep, napis, grafika", "10021" },
        {  65, "", "" },
        {  66, "grafika", "" },
        {  67, "napis, grafika", "" },
        {  68, "koszt, postep, napis, grafika", "10021 11052" },
        {  69, "napis, grafika", "" },
        {  70, "grafika", "" },
        {  71, "grafika", "" },
        {  72, "napis, grafika", "" },
        {  73, "koszt, postep, napis, grafika", "10021" },
        {  74, "grafika", "" },
        {  75, "grafika", "" },
        {  76, "napis, grafika", "" },
        {  77, "napis, grafika", "" },
        {  78, "napis, grafika", "" },
        {  79, "zloze", "" },
        {  80, "grafika", "" },
        {  81, "grafika", "" },
        {  82, "", "" },
        {  83, "postep, surowiec, grafika", "" },
        {  84, "surowiec", "" },
        {  85, "surowiec", "" },
        {  86, "surowiec", "" },
        {  87, "surowiec", "" },
        {  88, "surowiec", "" },
        {  89, "surowiec", "" },
        {  90, "surowiec", "" },
        {  91, "arsenal", "" },
        {  92, "koszt, grafika", "" },
        {  93, "biosonar, grafika", "" },
        {  94, "", "" },
        {  97, "grafika", "" },
        {  98, "grafika", "" },
        {  99, "grafika", "" },
        { 100, "grafika", "" },
        { 103, "grafika", "" },
        { 104, "grafika", "" },
        { 109, "grafika", "" },
        { 110, "grafika", "" },
        { 111, "napis, grafika", "" },
        { 112, "napis, grafika", "" },
        { 114, "napis, grafika", "" },
        { 115, "napis, grafika", "" },
    };
    n = int(sizeof(k) / sizeof(k[0]));
    return k;
}

}  // namespace bldui
