// Generated by gen_blddock.py, state 0/view 0; original 004cfa00/004cfbe0.
#pragma once
namespace blddock {
struct Def { const char *body; const char *color; int first,last; };
inline Def get(int type,int side) {
    if(type==50 && side==0) return {"dyaws_body","dyaws_id",0,19};
    if(type==50 && side==1) return {"dyabo_body","dyabo_id",0,16};
    if(type==92 && side==2) return {"plgen_body","plgen_id",0,18};
    if(type==64 && side==0) return {"worm_body","worm_id",0,16};
    if(type==64 && side==1) return {"worm_body","worm_id",0,16};
    if(type==73 && side==0) return {"dol_body","dol_id",16,31};
    if(type==73 && side==1) return {"dol_body","dol_id",16,31};
    return {nullptr,nullptr,0,0};
}
}
