// Generated by tools/gen_boatbob.py from ST.exe.
#pragma once
#include <cstdint>
namespace boatbob {
inline float offset(int phase) {
    static constexpr float wave[48]={0.13000000f,0.25999999f,0.38000000f,0.50000000f,0.61000001f,0.69999999f,0.79000002f,0.87000000f,0.92000002f,0.97000003f,0.99000001f,1.00000000f,0.99000001f,0.97000003f,0.92000002f,0.87000000f,0.79000002f,0.69999999f,0.61000001f,0.50000000f,0.38000000f,0.25999999f,0.13000000f,0.00000000f,-0.13000000f,-0.25999999f,-0.38000000f,-0.50000000f,-0.61000001f,-0.69999999f,-0.79000002f,-0.87000000f,-0.92000002f,-0.97000003f,-0.99000001f,-1.00000000f,-0.99000001f,-0.97000003f,-0.92000002f,-0.87000000f,-0.79000002f,-0.69999999f,-0.61000001f,-0.50000000f,-0.38000000f,-0.25999999f,-0.13000000f,0.00000000f};
    return phase>=0 && phase<48 ? wave[phase]*0.5f : 0.0f;
}
struct State {
    int phase=47; // STGameObj base initial value, before boat creation seeds it
    float displacement=0;
    int mode=1; // 1 continuous; 0 finish at neutral; other values hold
    bool neutral() const { return phase==47; }
};
// Returns 0 on reaching phase 47; 2 otherwise, including skipped odd ticks.
inline int Step(State &s,uint32_t worldTick) {
    if(s.mode!=1 && (s.mode!=0 || s.neutral())) return 2;
    if(worldTick&1) return 2;
    ++s.phase;
    int result=s.phase==47?0:2;
    if(s.phase==48) s.phase=0;
    s.displacement=offset(s.phase);
    return result;
}
}
