// Generated by tools/gen_cargorepair.py from the default ST.exe image.
#pragma once
namespace cargorepair {
inline constexpr int ticks[40]={500,750,1750,1250,1000,1000,750,500,750,1500,1500,750,500,1000,1750,1250,1000,1000,750,500,875,1500,1500,750,175,375,1000,1750,1000,500,1250,1125,1500,1000,1000,500,500,1750,1750,1750};
inline constexpr int firstResource[40]={0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0};
inline constexpr int metal[40]={200,400,1000,1000,700,800,800,600,200,1000,700,1000,300,500,1200,800,700,700,900,600,400,1000,1200,1000,0,0,0,0,0,0,0,0,0,0,0,0,500,1000,1000,0};
struct Quote { int hp=0,first=0,metal=0; };
inline Quote quote(int type,int hp,int maximum) {
    if(type<1 || type>40 || hp<=0 || maximum<=hp) return {};
    int i=type-1,add=maximum*25/ticks[i];
    if(add>maximum-hp) add=maximum-hp;
    return {add,firstResource[i]*add/maximum,metal[i]*add/maximum};
}
}
