// Generated by tools/gen_cassette.py; ST.exe ConusExplosion.
#pragma once
namespace cassette {
inline constexpr int ring5[5][2] = {
    {10000,0},
    {3090,9510},
    {-8090,5877},
    {-8090,-5877},
    {3090,-9510},
};
inline constexpr int ring7[7][2] = {
    {10000,0},
    {6234,7818},
    {-2225,9749},
    {-9009,4338},
    {-9009,-4338},
    {-2225,-9749},
    {6234,-7818},
};
inline int childDamage(bool ion) {
    return ion ? 20 : 70;
}
}
