#pragma once
#include <cstdint>
namespace cargotransfer {
inline int crateSize(uint32_t kind) { return kind==220?5:kind==221?3:kind==222?20:1; }
struct Cargo {
    int gold=0,corium=0,metal=0;
    int total() const { return gold+corium+metal; }
    int &of(uint32_t kind) { return kind==220?gold:kind==221?corium:metal; }
    int crates() const { return gold/5+corium/3+metal/20; }
    uint32_t nextKind() const { return gold?220:corium?221:metal?222:0; }
};
struct Transfer { uint32_t kind=0;int amount=0; };
// LoadRC 004692c8..00469369: one crate; gold, then corium, then metal.
inline Transfer unload(Cargo &cargo) {
    uint32_t kind=cargo.nextKind();
    if(!kind) return {};
    int amount=crateSize(kind);
    if(cargo.of(kind)<amount) return {}; // partial crates are never generated by the loader
    cargo.of(kind)-=amount;return {kind,amount};
}
inline int load(Cargo &cargo,uint32_t kind,int &store) {
    if(kind<220 || kind>222 || cargo.crates()>=40) return 0;
    int amount=crateSize(kind);
    // TakeFromDeposit 004e1930 drains the remaining fraction too; LoadRC
    // adds a crate only when the requested amount was returned in full.
    if(store<amount) { store=0;return 0; }
    store-=amount;cargo.of(kind)+=amount;return amount;
}
// Original transfer substates increment their counter, then test counter % 10 == 1.
struct Clock {
    double remainder=0;uint32_t tick=0;
    void reset() { remainder=0;tick=0; }
    int advance(float secs) {
        if(secs<=0) return 0;
        remainder+=double(secs)*25;
        unsigned ticks=unsigned(remainder+1e-6);
        remainder-=ticks;if(remainder<0) remainder=0;
        int count=0;
        while(ticks--) if(++tick%10==1) ++count;
        return count;
    }
};
}
