#pragma once
// Generated by tools/gen_footprint.py from ST.exe; placement 004ae0b0.
namespace footprint {
inline int building(int type) {
    static constexpr unsigned char large[66] = {
        1,1,1,1,0,1,0,0,0,1,1,1,0,0,0,1,
        0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,
        1,1,0,0,0,0,0,0,0,1,1,1,0,1,1,0,
        1,1,1,0,0,0,0,0,0,0,1,1,1,0,1,0,
        0,1,
    };
    return type>=50 && type<=115 ? 1+large[type-50] : 1;
}
}
