// Generated by tools/gen_projectile_media.py; STTorpC::GetMessage 006406d0.
// ST.exe SHA256: 61dc5322b1318da95eca45a0a3c956a373545bae2f857744e2487cd15ad45b0f
#pragma once
namespace projmedia {
struct Media { const char *sprite; int launch, impact; bool directional; const char *explosion; };
inline Media get(int projectile) {
    switch (projectile) {
    case 0x96: return {"atorsm", 1103, 1104, true, "exptsm"};
    case 0x97: return {"atorme", 1105, 1106, true, "exphfs"};
    case 0x98: return {"atorla", 1107, 1108, true, "exptla"};
    case 0x99: return {"acas0", 1109, 1110, true, "expcshl"};
    case 0x9a: return {"aemtor", 1111, 1112, true, "Expb26"};
    case 0x9b: return {"alray1", 1169, 1170, true, "exprlas"};
    case 0x9c: return {"alray0", 1131, 1132, true, "expllas"};
    case 0x9d: return {"alray1", 1133, 1134, true, "exprlas"};
    case 0x9e: return {"alray2", 1135, 1136, true, "exphlas"};
    case 0x9f: return {"ahfl", 1125, 1126, false, "exphfs"};
    case 0xa0: return {"ahfh", 1127, 1128, false, "exphfl"};
    case 0xa1: return {"pr_torp", 1129, 1130, false, "exphfl"};
    case 0xa3: return {"ahfl", 1167, 1168, false, "expcshl"};
    case 0xa4: return {"ahfl", 1171, 1172, false, "Expb23"};
    case 0xa5: return {"satlas", 1157, 1158, false, "exphfs"};
    case 0xac: return {"aspltor", 1139, 1140, true, "expemag"};
    case 0xad: return {"neuro", 1153, 1154, true, "explprl"};
    case 0xae: return {"agcan", 1165, 1166, false, "expgcan"};
    case 0xb4: return {"atorsm", 1137, 1138, true, "exptsm"};
    case 0xb6: return {"eshell", 1145, 1146, true, "expll01"};
    case 0xb7: return {"ionbomb", 1147, 1148, true, "explioc"};
    case 0xb8: return {"biaacc", 1151, 1152, true, "expll02"};
    case 0xb9: return {"ion_cs", 1149, 1150, true, "explioc"};
    case 0xba: return {"eshell", 1155, 1156, true, "expll01"};
    case 0xbf: return {"ahfh", 1159, 1160, false, "exppar"};
    default: return {nullptr, 0, 0, false, "exphfs"};
    }
}
} // namespace projmedia
