// Generated by tools/gen_production.py from ST.exe.
#pragma once
#include <algorithm>
namespace production {
inline float seconds(int type) {
    static const int ticks[40]={500,750,1750,1250,1000,1000,750,500,750,1500,1500,750,500,1000,1750,1250,1000,1000,750,500,875,1500,1500,750,175,375,1000,1750,1000,500,1250,1125,1500,1000,1000,500,500,1750,1750,1750};
    return type>=1 && type<=40 ? float(std::max(1,ticks[type-1]/100)*100)/25.0f : 0;
}
}
